---
name: "YAS-209 Bridge"
description: "A custom bridge for the events from YAS-209"
version: "0.1.2"
slug: "yas_209_bridge"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
options:
  listen_ip: 192.168.1.X
  listen_port: 50420
  source_port: 50420
  yas_209_ip: 192.168.1.Y
  sftp_hostname: homeassistant.local
  sftp_username: root
  sftp_key_filepath: .ssh/id_rsa
schema:
  listen_ip: str
  listen_port: int
  source_port: int
  yas_209_ip: str
  sftp_hostname: str
  sftp_username: str
  sftp_key_filepath: str
ports:
  50420/tcp: 50420
