---
name: PR Auto-Update
on:
  push:
    branches:
      - develop

jobs:
  autoupdate:
    name: PR Auto-Update
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_FILTER: labelled
          PR_LABELS: "keep-updated"
          MERGE_CONFLICT_ACTION: "ignore"
